language: python
python:
  - 3.8
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings
  matrix:
    - DJANGO=2.2
install:
  - pip install -q Django==$DJANGO django-debug-toolbar>=1.0
script: python -m tests.test_toolbar
